# Generated by Django 5.0.3 on 2024-04-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity', models.CharField(max_length=500)),
                ('Activity_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currencey', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('Pak', 'pakistan rupees')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='projectAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('fax_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('work_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('project_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('Number_hours', models.PositiveIntegerField()),
                ('Total_cost_resources', models.DecimalField(decimal_places=2, max_digits=20)),
                ('option_period', models.CharField(max_length=250)),
            ],
        ),
    ]
