# Generated by Django 5.0.3 on 2024-04-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_project_detail_delete_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currencey', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('Pak', 'pakistan rupees')], max_length=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('Number_hours', models.PositiveIntegerField()),
                ('Total_cost_resources', models.DecimalField(decimal_places=2, max_digits=20)),
                ('option_period', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectinformation')),
            ],
        ),
    ]
